version: '3.7'

services:

  db:

    container_name: "mysql-server"

    image: mysql

    environment:

      MYSQL_ROOT_PASSWORD: "Qwerty1234567"

    ports:
      - "3306:3306"

    volumes:

      - "/home/deployment/mysql/conf.d:/etc/mysql/conf.d"

      - mysql-data:/var/lib/mysql




volumes:

  mysql-data: